### ISSUE TITLE
Docs: Feedback for Securing User Sessions

### ISSUE THREAD

**Issue by gokhansari** [hazelcast/management-center-docs#244]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/deploy-manage/pages/sessions.adoc)

User not logged out after session timeout duration: https://hazelcast.atlassian.net/browse/MC-1918
Background communication activities between ui and backend (like periodic polling/websocket connection) prevent user from being logged out.

**Comment by sertugkaya** [comment]
Here's the part that needs to be clarified:

"the background communication between UI and the backend is authenticated with the same user session so each background call postpones the session timeout window. It turned out that the current session timeout property (hazelcast.mc.session.timeout.seconds) is effective only after the browser tab is closed or after the browser suspends the background activity of the webpage. We will update the documentation to reflect this in more clarity. "
